apiVersion: v1
kind: ConfigMap
metadata:
    name: devnet-chatbot-roomadd-cfgmap
    namespace: devnet-tools-prod
data:
  room.whitelist: |-
    # List of rooms which the bot is allowed to perform operations on, e.g.:
    #c4699750-db27-11e5-b4f4-0abc030ad0c3
    c4699750-db27-11e5-b4f4-fbf227cffaf3
    4fe94610-f061-11e5-b8ce-113f8dfc14be
  user.blacklist: |-
    # List of users which will NOT be operated on, e.g.:
    # blacklisted@example.com
  spark.secrets: |-
    [User]
    accessToken =
